import dotenv from "dotenv";

dotenv.config();

const { DISCORD_TOKEN, DISCORD_CLIENT_ID, DISCORD_GUILD_ID, DISCORD_EMBED_COLORS, DISCORD_WELCOME_CHANNEL_ID, DISCORD_MEMBER_ROLE_ID, TEMP_VOICE_CHANNEL_ID } = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID || !DISCORD_GUILD_ID || !DISCORD_EMBED_COLORS || !DISCORD_WELCOME_CHANNEL_ID || !DISCORD_MEMBER_ROLE_ID || !TEMP_VOICE_CHANNEL_ID) {
    throw new Error("Missing environment variables");
}

export const config = {
    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,
    DISCORD_GUILD_ID,
    DISCORD_EMBED_COLORS,
    DISCORD_WELCOME_CHANNEL_ID,
    DISCORD_MEMBER_ROLE_ID,
    TEMP_VOICE_CHANNEL_ID
};